language: node_js
node_js:
- '8'
script:
- npm run test:ci
after_success:
- node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info --COVERALLS_SERVICE_NAME="travis-pro" --COVERALLS_REPO_TOKEN="${COVERALLS_TOKEN}"
env:
  global:
    secure: CEdo3apeeRPVXwaNAboQbwZCQXpsiKfsTWrG1PvGMDZS88/apZTIFbusWq+geRzDwU2Xmb3AG54gA8iEphNNvsnwNl4tv2nQ4r6sXaM+NKVkVUqfa72XbhbaBWExTsqVEyMiUBIV0EBh1ufGJMe7ZwabxEsYN+OXpRUDcbJS7j2ixr06EJA9aZU/sXNjI9mjMyUREoFy8Y2vt0Rm3D5XRr9tZWYs6h3Sob/y7V6r4IesaYO4NNArYacXsXj/xR6AajxuxrNhiX5i4T11B15xSQV5G5iN8I3FMDYOxeB37PNYCQr/kiXGpiRENHIPv7z82OO3B0Ngbtn4iNW4UGOBfDtlk6g/Jv7qsuieUbduklOTvMtn9Kd7jkhqbCKdlm3sn4UUb9sWUUUcK37TuVRh6a6K71QOEnXhD/rggnsYv19amoWVP132416fLTCmiO4WodYHxWClJ4I7oYVn4N1f6H/OuHpkPFxtZGg6TIOWIYrROODPMb3n0zHyurfYTVxhByNwYUVqiioJ4tMxcAsYJM3Hjlo+204BttbdcZh6GyqsprmSHaw0iXbcJGA/yIJz2d4eK6qB8pzVDfS0ks3n2iSWaitrRTiT9NNDtaWFbOl30DGcZjFUyUN3cLuaZkKx+JEy2T7Thh7Rz+o4FkXNPo3aYAPM0U3VPiaQfVYgz8s=
